### PR TITLE
Book related issues

### LINKED ISSUE #179: Custom frames: Books should reshuffle their contents whenever an item is removed from them
In https://github.com/AzerothWarsLR/WarcraftLegacies/pull/135, we made it so that Artifact Books shuffle their contents to fit the available space when an Artifact is removed from the game. We should move that logic to the generic Book/Page/Card classes so that it works for all other Books. PowerBook is of particular interest.

### LINKED ISSUE #281: Organize Artifact menu items by alphabetical order

### LINKED ISSUE #417: Books throw ArgumentOutOfRangeException when spam clicking Next and Previous Buttons
This does not cause any crashes. 
It does print the exception on the screen though.

### PR DESCRIPTION
**Pull request by TracyTheBoy**
Closes #179 
Closes #281 
Closes #417 

Solving #179 #281 and bug that was reintroduced in the commit for fixing #372

I was so unhappy with what I did in the other PR that I decided to just start over.
So this time all I basically did is build on 'IBook' interface.
I made all the buttons that were private before, public and part of the api and I also added methods for each of the buttons expected funtions.
This now allows other systems to work with the book without the use of its buttons.
Its also keeping it flexible by allowing consumer code to decide what is supposed to happen when a button is pressed because they can override the 'OnClick' action of each button.
Right now the `LauncherButton `is part of `IBook` but when that is not needed anymore when the `AugmentBook` is introduced you could easily subclass `Book` or make another interface and move `LauncherButton` along with  `Title` and `LauncherParent` in there and you're good. Or so I think anyway.

All the LauncherButton code in the `ArtifactManager` could be moved to `Book` theoretically but I decided to leave it for now to not screw up the desync issues you fixed in #372.

### CODE REVIEW

**Comment by YakaryBovine** [comment]
Brilliant, this is way better. I'll take a proper look after work but I can't see any issues.
P.S. since we've exposing so much Book logic to clients I wonder if we should just take make Book<T> concrete, making it also take in some kind of observable manager as another type constructor. E.g. Book<PageType, ObservableManagerType>. That way Book could be a non-inheritable concrete class that you just configure when you construct it. But, these changes are good even if we don't do that.

File: src/MacroTools/BookSystem/IBook.cs [hunk 1]
```diff
@@ -15,15 +16,54 @@ public interface IBook
...
+
+    /// <summary>
+    /// A button for launching of the book
+    /// </summary>
+    public Button LauncherButton { get; set; }
+
+    /// <summary>
+    /// A button for moving to the next page of the book
+    /// </summary>
+    public Button MoveNextButton { get; set; }
```
Comment (YakaryBovine) [inline src/MacroTools/BookSystem/IBook.cs:38]: I don't think we want to expose the setter on these; I can't imagine a scenario where it's valid for a consumer to arbitrarily modify the Next Button, even if it might be valid to modify what it does. Maybe we should just expose the Get?

LauncherButton seems valid to expose the Set.

**Comment by TracyTheBoy** [comment]
> Brilliant, this is way better. I'll take a proper look after work but I can't see any issues. P.S. since we've exposing so much Book logic to clients I wonder if we should just take make Book concrete, making it also take in some kind of observable manager as another type constructor. E.g. Book<PageType, ObservableManagerType>. That way Book could be a non-inheritable concrete class that you just configure when you construct it. But, these changes are good even if we don't do that.

Yea I like that idea. Having an abstract book class is sort of redundant now that `IBook` exists. 
I did play around with making Book concrete but I ultimately decided to not make too many changes because I wanted to focus on the solving the issues.
And I thought an extra ticket would make more sense for the revision of the system.

**Comment by YakaryBovine** [comment]
Good stuff! P.S. I have the #298 ticket for that appsettings issue ;)
