### PR TITLE
Stonemaul fix

### LINKED ISSUE #481: Stonemaul base instantly turned hostile after Frostwolf completed The Chieftain's Challenge
image
image

This is because the quest goal conflicts with that of Ruins of Stonemaul for Dragonmaw.
image
image

### PR DESCRIPTION
**Pull request by SavanticIO**
Added ObjectiveUnitIsDead
Updated the kill Kor'Gall quests to use new ObjectiveUnitIsDead

Closes #481 

An alternate way to do this would have been to make Kor'Gall a legend and use ObjectiveLegendDead

### CODE REVIEW

File: src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+using WCSharp.Shared.Data;
+using static War3Api.Common;
+
+namespace MacroTools.QuestSystem.UtilityStructs
+{
+  public class ObjectiveUnitIsDead : Objective
+  {
+    public ObjectiveUnitIsDead(unit unitToKill)
+    {
+      trigger trig = CreateTrigger();
```
Comment (YakaryBovine) [inline src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs:13]: Up to you, but you can use Linq-style syntax if you want. E.g:

```cs
CreateTrigger()
   .RegisterUnitEvent(unitToKill, EVENT_UNIT_DEATH)
   .AddAction(trig, OnUnitDeath)
```

File: src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+                         GetOwningPlayer(Target) == Player(PLAYER_NEUTRAL_AGGRESSIVE);
+    }
+
+    public override Point Position => new(GetUnitX(Target), GetUnitY(Target));
+
+    public unit Target { get; }
+
+    private void OnUnitDeath()
+    {
+      Progress = QuestProgress.Complete;
```
Comment (YakaryBovine) [inline src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs:29]: This is so short it might as well just be part of the trigger declaration. E.g.:

```cs
TriggerAddAction(() => { Progress = QuestProgress.Complete; });
```

File: src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs [hunk 3]
```diff
@@ -0,0 +1,43 @@
+﻿using MacroTools.Extensions;
+using MacroTools.FactionSystem;
+using WCSharp.Events;
+using WCSharp.Shared.Data;
+using static War3Api.Common;
+
+namespace MacroTools.QuestSystem.UtilityStructs
+{
+  public class ObjectiveUnitIsDead : Objective
```
Comment (YakaryBovine) [inline src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs:9]: Add `sealed` keyword IMO; not designed to be inherited.

**Review by YakaryBovine — DISMISSED** [review]
Good solution; better than using `ObjectiveLegendIsDead` I think. Have left a few syntax suggestions. (I know that code you referenced to create this may not have followed these suggestions)

File: src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs (hunk 1 above)
Comment (SavanticIO) [reply src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs]: I'm not as used to using Linq-style syntax but makes sense and one to keep in mind.

File: src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs (hunk 2 above)
Comment (SavanticIO) [reply src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs]: Done

File: src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs (hunk 3 above)
Comment (SavanticIO) [reply src/MacroTools/QuestSystem/UtilityStructs/ObjectiveUnitIsDead.cs]: Done

**Review by YakaryBovine — APPROVED** [review]
